### ISSUE TITLE
bug: worker without input parameter throws an exception

### ISSUE THREAD

**Issue by rami-nk** [Miragon/miranum-connect#190]
**Describe the bug**

When a miranum worker is defined without providing an input parameter, the `CamundaXWorkerAdapter` throws an exception. The issue occurs in both Camunda 7 and Camunda 8 environments.

An example worker that triggers the exception:

```java
@Worker(type = "sendMessage")
public Answer sendMessage() { // Here is no input parameter
    log.info("Inside of SendMessage-Worker.");
    return new Answer("answer");
}
```

The exception for Camunda8:
```less
.Camunda8WorkerAdapter    : general exception detected

java.lang.IllegalArgumentException: Unrecognized Type: [null]
	at com.fasterxml.jackson.databind.type.TypeFactory._fromAny(TypeFactory.java:1421) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.type.TypeFactory.constructType(TypeFactory.java:752) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3740) ~[jackson-databind-2.15.2.jar:2.15.2]
	at io.camunda.zeebe.client.impl.ZeebeObjectMapper.fromJson(ZeebeObjectMapper.java:53) ~[zeebe-client-java-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.client.impl.response.ActivatedJobImpl.getVariablesAsType(ActivatedJobImpl.java:132) ~[zeebe-client-java-8.2.8.jar:8.2.8]
	at io.miragon.miranum.connect.adapter.in.c8.worker.Camunda8WorkerAdapter.execute(Camunda8WorkerAdapter.java:38) ~[classes/:na]
	at io.miragon.miranum.connect.adapter.in.c8.worker.Camunda8WorkerAdapter.lambda$subscribe$0(Camunda8WorkerAdapter.java:29) ~[classes/:na]
	at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.executeJob(JobRunnableFactory.java:44) ~[zeebe-client-java-8.2.8.jar:8.2.8]
	at io.camunda.zeebe.client.impl.worker.JobRunnableFactory.lambda$create$0(JobRunnableFactory.java:39) ~[zeebe-client-java-8.2.8.jar:8.2.8]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```

In the Camunda8WorkerAdapter it is the call of the `job.getVariablesAsType(null)` that causes the problem:

https://github.com/Miragon/miranum-connect/blob/acce2cb4cac0aea510a7e28d9daabda2235c9c09/connect/connect-c8/worker-adapter-c8/src/main/java/io/miragon/miranum/connect/adapter/in/c8/worker/Camunda8WorkerAdapter.java#L37C2-L39

**To Reproduce**
1. Checkout branch `bug/worker-null-input`
2. Start the Camunda7 or 8 Application of the simple example (The worker is adapted to not have a input parameter)
3. Deploy and start the bpmn 
4. See error in the applicaton console

**Expected behavior**
There should not be an error, because it is perfectly fine for a worker to not have any input type.

**Comment by rami-nk** [comment]
@dominikhorn93 Can you confirm that this issue exists?
